services:
  mona:
    container_name: mona
    image: mona
    build:
      context: mona
      dockerfile: Dockerfile
    volumes:
      - ${SRC_DIR}:/src_dir
      - ${DATA_DIR}:/data_dir
    tty: true
    environment:
      SRC_DIR: /src_dir
      DATA_DIR: /data_dir
  
  panther:
    container_name: panther
    image: panther
    build:
      context: panther
      dockerfile: Dockerfile
    volumes:
      - ${DATA_DIR}:/data_dir
    tty: true
    environment:
      DATA_DIR: /data_dir
      ES_URL: http://es01:9200
      ES_USER: ${ELASTIC_USER}
      ES_PASSWORD: ${ELASTIC_PASSWORD}
 
  #  queen:
  #    container_name: queen-dev
  #    image: queen-dev
  #  build:
  #    context: queen
  #    dockerfile: Dockerfile.dev
  #  volumes:
  #    - .:/workspaces:cached
  #  tty: true
  #  restart: always
  #  #environment:
  #  #  GROONGA_URL: http://groonga-dev:10041/d
  #  #ports:
  #  #  - 28000:8000
 
  fox:
    container_name: fox
    image: fox
    build:
      context: fox
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ${WWW_ROOT}:/app/dist
      - ${DATA_DIR}:/app/public/content

  joker:
    container_name: joker
    image: joker
    tty: true
    build:
      context: joker
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspaces:cached
    #ports:
    #  - 20041:10041

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.3
    container_name: phantom-elasticsearch
    environment:
      xpack.security.enabled: false
      discovery.type: single-node
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    restart: always

  setup:
    image: curlimages/curl:8.5.0
    depends_on:
      - es01
    entrypoint: >
      sh -c "
         echo 'Waiting for Elasticsearch...';
      until curl -s http://elasticsearch:9200 >/dev/null; do sleep 1; done;
      echo 'Creating index patent-documents...';
      curl -X PUT http://elasticsearch:9200/patent-documents -H 'Content-Type: application/json' -d '
      {
        \"settings\": {
          \"number_of_shards\": 1,
          \"number_of_replicas\": 0
        }
      }';
      echo 'Done.';
      "
    restart: "no"

  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.3
    container_name: phantom-kibana
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - xpack.security.enabled=true
      - xpack.security.authc.providers=[]
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - I18N_LOCALE=${I18N_LOCALE}
    mem_limit: ${MEM_LIMIT}
    depends_on:
      - es01


volumes:
  es-data:

