services:
  mona:
    container_name: mona
    image: mona
    build:
      context: mona
      dockerfile: Dockerfile
    volumes:
      - ${SRC_DIR}:/src_dir
      - ${DATA_DIR}:/data_dir
    tty: true
    environment:
      SRC_DIR: /src_dir
      DATA_DIR: /data_dir
      OMP_THREAD_LIMIT: 1
  
  panther:
    container_name: panther
    image: panther
    build:
      context: panther
      dockerfile: Dockerfile
    volumes:
      - ${DATA_DIR}:/data_dir
      - ${EXTRA_DATA_DIR}:/extra_dir
    tty: true
    environment:
      DATA_DIR: /data_dir
      ES_URL: http://es01:9200
      ES_USER: ${ELASTIC_USER}
      ES_PASSWORD: ${ELASTIC_PASSWORD}
 
  #  queen:
  #    container_name: queen
  #    image: queen
  #  build:
  #    context: queen
  #    dockerfile: Dockerfile
  #  volumes:
  #    - .:/workspaces:cached
  #  tty: true
  #  restart: always
  #  #environment:
  #  #  GROONGA_URL: http://groonga-dev:10041/d
  #  #ports:
  #  #  - 28000:8000
 
  fox:
    container_name: fox
    image: fox
    build:
      context: fox
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ${WWW_ROOT}:/app/dist
      - ${DATA_DIR}:/app/public/content

  joker:
    container_name: joker
    image: joker
    build:
      context: joker
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
      ES_URL: http://es01:9200
      ES_USER: ${ELASTIC_USER}
      ES_PASSWORD: ${ELASTIC_PASSWORD}
      IMAGE_BASE_URL: /content
      DOCUMENT_BASE_URL: /docs

  es01:
    image: phantom-lasticsearch
    container_name: phantom-elasticsearch
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      xpack.security.enabled: false
      discovery.type: single-node
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - ${WWW_ROOT}:/usr/share/nginx/html
    ports:
      - ${NGINX_PORT}:8080

volumes:
  es-data:

