services:
  fox-dev:
    container_name: fox-dev
    image: node:24-bookworm
    tty: true
    environment:
      NODE_ENV: development
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
    volumes:
      - .:/workspaces:cached
      - ${DATA_DIR}:/data_dir
      - ${LOG_DIR_FOX}:/var/log/fox
    networks:
      - dev-net

  joker-dev:
    container_name: joker-dev
    image: node:24-bookworm
    volumes:
      - .:/workspaces:cached
      - ${LOG_DIR_JOKER}:/var/log/joker
      - ${DATA_DIR}:/data_dir
    environment:
      NODE_ENV: development
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
      ES_URL: http://es01-dev:9200
      ES_USER: ${ELASTIC_USER}
      ES_PASSWORD: ${ELASTIC_PASSWORD}
      IMAGE_BASE_URL: /images
      DOCUMENT_BASE_URL: /docs
    tty: true
    networks:
      - dev-net

  es01-dev:
    image: phantom-lasticsearch
    container_name: phantom-elasticsearch-dev
    build:
      dockerfile: docker/Dockerfile.es
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      network.host: 0.0.0.0
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - es-data-dev:/usr/share/elasticsearch/data
    networks:
      - dev-net
    ports:
      - 9200:9200
    restart: always


  nginx-dev:
    container_name: nginx-dev
    image: nginx-dev
    build:
      context: nginx
      dockerfile: Dockerfile.dev
    volumes:
      - ${DATA_DIR}:/images
      - ${WWWROOT_DIR}:/usr/share/nginx/html
    ports:
      - ${DEV_NGINX_PORT}:38080
    networks:
      - dev-net

volumes:
  es-data-dev:

networks:
  dev-net:
    name: phantom-dev-net
    driver: bridge
