services:
  mona:
    container_name: mona-dev
    image: mona-dev
    build:
      context: mona
      dockerfile: Dockerfile.dev
    volumes:
      - ${SRC_DIR}:/src_dir
      - ${DATA_DIR}:/data_dir
      - .:/workspaces:cached
    tty: true
    environment:
      SRC_DIR: /src_dir
      DATA_DIR: /data_dir
  
  panther:
    container_name: panther-dev
    image: panther-dev
    build:
      context: panther
      dockerfile: Dockerfile.dev
    volumes:
      - ${DATA_DIR}:/data_dir
      - .:/workspaces:cached
    tty: true
    environment:
      DATA_DIR: /data_dir
      ES_URL: http://es01:9200
      ES_USER: ${ELASTIC_USER}
      ES_PASSWORD: ${ELASTIC_PASSWORD}
 
  queen:
    container_name: queen-dev
    image: queen-dev
    build:
      context: queen
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspaces:cached
    tty: true
    restart: always
    #environment:
    #  GROONGA_URL: http://groonga-dev:10041/d
    #ports:
    #  - 28000:8000
 
  fox:
    container_name: fox-dev
    image: fox-dev
    build:
      context: fox
      dockerfile: Dockerfile.dev
    tty: true
    volumes:
      - .:/workspaces:cached
      - ${DATA_DIR}:/workspaces/fox/public/content

  joker:
    container_name: joker-dev
    image: joker-dev
    build:
      context: joker
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspaces:cached
    environment:
      ES_URL: http://es01:9200
      ES_USER: ${ELASTIC_USER}
      ES_PASSWORD: ${ELASTIC_PASSWORD}
    tty: true
    #ports:
    #  - 20041:10041

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.3
    container_name: phantom-elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - network.host=0.0.0.0
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - es-data:/usr/share/elasticsearch/data
    #mem_limit: ${MEM_LIMIT}
    #ulimits:
    #  memlock:
    #    soft: -1
    #    hard: -1

  setup:
    image: curlimages/curl:8.5.0
    depends_on:
      - es01
    entrypoint: >
      sh -c "
         echo 'Waiting for Elasticsearch...';
      until curl -s http://elasticsearch:9200 >/dev/null; do sleep 1; done;
      echo 'Creating index patent-documents...';
      curl -X PUT http://elasticsearch:9200/patent-documents -H 'Content-Type: application/json' -d '
      {
        \"settings\": {
          \"number_of_shards\": 1,
          \"number_of_replicas\": 0
        }
      }';
      echo 'Done.';
      "
    restart: "no"
 
  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.3
    container_name: phantom-kibana
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - xpack.security.enabled=true
      - xpack.security.authc.providers=[]
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - I18N_LOCALE=${I18N_LOCALE}
    mem_limit: ${MEM_LIMIT}
    depends_on:
      - es01

  nginx:
    container_name: nginx-dev
    image: nginx-dev
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - ${WWW_ROOT}:/usr/share/nginx/html
    ports:
      - ${NGINX_PORT}:8080



volumes:
  es-data:

