services:
  mona:
    container_name: mona
    image: ghcr.io/hyperion13th144m/phantom-mona:develop
    volumes:
      - ${SRC_DIR}:/src_dir
      - ${DATA_DIR}:/data_dir
      - ${LOG_DIR_MONA}:/var/log/mona
    tty: true
    environment:
      SRC_DIR: /src_dir
      DATA_DIR: /data_dir
      OMP_THREAD_LIMIT: 1
  
  panther:
    container_name: panther
    image: ghcr.io/hyperion13th144m/phantom-panther:develop
    volumes:
      - ${DATA_DIR}:/data_dir
      - ${EXTRA_DATA_DIR}:/extra_dir
      - ${LOG_DIR_PANTHER}:/var/log/panther
    tty: true
    environment:
      DATA_DIR: /data_dir
      ES_URL: http://es01:9200
      ES_USER: ${ELASTIC_USER}
      ES_PASSWORD: ${ELASTIC_PASSWORD}
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo

  fox:
    container_name: fox
    image: ghcr.io/hyperion13th144m/phantom-fox:develop
    volumes:
      - ${DATA_DIR}:/data_dir
      - ${LOG_DIR_FOX}:/var/log/fox

  joker:
    container_name: joker
    image: ghcr.io/hyperion13th144m/phantom-joker:develop
    volumes:
      - ${LOG_DIR_JOKER}:/var/log/joker
    environment:
      NODE_ENV: production
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
      ES_URL: http://es01:9200
      ES_USER: ${ELASTIC_USER}
      ES_PASSWORD: ${ELASTIC_PASSWORD}
      IMAGE_BASE_URL: /images
      DOCUMENT_BASE_URL: /docs

  es01:
    image: ghcr.io/hyperion13th144m/phantom-elasticsearch:develop
    container_name: phantom-elasticsearch
    environment:
      xpack.security.enabled: false
      discovery.type: single-node
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    restart: always

  nginx:
    image: ghcr.io/hyperion13th144m/phantom-nginx:develop
    container_name: phantom-nginx
    volumes:
      - ${DATA_DIR}:/usr/share/nginx/html
    ports:
      - ${NGINX_PORT}:8080

volumes:
  es-data:

