FROM python:3.14-slim

ARG USERNAME=pyuser
ARG GROUPNAME=pygroup
ARG UID=1000
ARG GID=1000
ENV TZ=Asia/Tokyo

RUN groupadd -g $GID $GROUPNAME && useradd -m -s /bin/sh -u $UID -g $GID $USERNAME
RUN pip install uv
RUN mkdir /var/log/panther && chown $USERNAME:$GROUPNAME /var/log/panther

USER $USERNAME
WORKDIR /app
COPY . ./
RUN uv sync
RUN uv build

ENTRYPOINT [ "uv", "run", "src/panther/main.py" ]
