FROM python:3.14-bookworm

ARG USERNAME=pyuser
ARG GROUPNAME=pygroup
ARG UID=1000
ARG GID=1000
ENV TZ=Asia/Tokyo

RUN groupadd -g $GID $GROUPNAME && useradd -m -s /bin/bash -u $UID -g $GID $USERNAME

RUN apt-get update
RUN python -m pip install --upgrade pip
RUN pip install poetry

WORKDIR /app
COPY --chown=$USERNAME:$GROUPNAME pyproject.toml poetry.lock ./
RUN poetry install --no-root
USER $USERNAME
COPY --chown=$USERNAME:$GROUPNAME . .

CMD [ "python" ]
