# Source - https://stackoverflow.com/a
# Posted by fylie, modified by community. See post 'Timeline' for change history
# Retrieved 2026-01-11, License - CC BY-SA 4.0

FROM docker.elastic.co/elasticsearch/elasticsearch:8.19.9

RUN bin/elasticsearch-plugin install analysis-icu
RUN bin/elasticsearch-plugin install analysis-kuromoji

