services:
  skull-dev:
    build:
      context: services/skull
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspaces:cached
    tty: true
    entrypoint: ["sh", "-c", "sleep infinity"]
