services:
  skull-dev:
    volumes:
      - .:/workspaces:cached

      # skull generates its package to /pkgs directory
      # for building container(e.g. navi) that requires the pakcage
      # in development environment.
      - ./var/pkgs/skull:/pkgs
    tty: true
    entrypoint: ["sh", "-c", "sleep infinity"]
