server {
  listen 38080;
  server_name _;

  index  index.html index.htm;
  include /etc/nginx/mime.types;

  location / {
      root /usr/share/nginx/html/;
  }
  location /images {
      alias /images/;
  }
}

