services:
  noir-dev:
    build:
      context: services/noir
      dockerfile: Dockerfile.dev
    user: pyuser
    volumes:
      - .:/workspaces:cached
    tty: true
    entrypoint: ["sh", "-c", "sleep infinity"]
